
[opt_allocation_x_re_SCO,avg_SCO_NL,ga_process_time_SCO]=ga_solver_simple(TotalSTA, ...
    Total_packet,Th_request_list_STA,PER_request_list,alpha,DR_convergence_rate, ...
    PER_convergence_rate,DR_per_packet,PER_per_packet,cutpoint,RU_SCO, ...
    DR_per_packet_PO,PER_per_packet_PO,MaxGenerations_simple);
